# Generated by Django 5.2.17 on 2026-08-12 00:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import inovasi.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('singkatan', models.CharField(blank=True, max_length=40)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'OPD',
                'verbose_name_plural': 'OPD',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.PositiveIntegerField(unique=True)),
                ('window_buka', models.DateField(blank=True, null=True)),
                ('window_tutup', models.DateField(blank=True, null=True)),
                ('pembagi_minimal', models.PositiveSmallIntegerField(default=12, help_text='Jumlah inovasi pembagi rata-rata kematangan. 12 pada 2026.')),
                ('min_urusan_yandas', models.PositiveSmallIntegerField(default=5, help_text='Urusan wajib pelayanan dasar minimal. 5 pada 2026, 6 pada 2027.')),
                ('aktif', models.BooleanField(default=False)),
                ('catatan', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-tahun'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('peran', models.CharField(choices=[('admin', 'Administrator'), ('verifikator', 'Verifikator'), ('operator', 'Operator OPD')], default='operator', max_length=20)),
                ('nip', models.CharField(blank=True, max_length=25)),
                ('telepon', models.CharField(blank=True, max_length=25)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('opd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pengguna', to='inovasi.opd')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Inovasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('tahapan', models.CharField(choices=[('inisiatif', 'Inisiatif'), ('uji_coba', 'Uji Coba'), ('penerapan', 'Penerapan')], default='inisiatif', max_length=20)),
                ('inisiator', models.CharField(choices=[('kepala_daerah', 'Kepala Daerah'), ('dprd', 'Anggota DPRD'), ('asn', 'ASN'), ('perangkat_daerah', 'Perangkat Daerah'), ('masyarakat', 'Masyarakat')], default='perangkat_daerah', max_length=25)),
                ('nama_inisiator', models.CharField(blank=True, max_length=200)),
                ('klasifikasi', models.CharField(choices=[('perangkat_daerah', 'Inovasi Perangkat Daerah'), ('desa', 'Inovasi Desa'), ('masyarakat', 'Inovasi Masyarakat')], default='perangkat_daerah', max_length=20)),
                ('jenis', models.CharField(choices=[('digital', 'Digital'), ('non_digital', 'Non-Digital')], default='non_digital', max_length=15)),
                ('bentuk', models.CharField(choices=[('tata_kelola', 'Inovasi Tata Kelola Pemerintahan Daerah'), ('pelayanan_publik', 'Inovasi Pelayanan Publik'), ('lainnya', 'Inovasi Daerah Lainnya')], default='pelayanan_publik', max_length=20)),
                ('urusan', models.CharField(blank=True, help_text='Urusan pemerintahan utama', max_length=100)),
                ('lintang', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bujur', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('asta_cita', models.CharField(blank=True, choices=[('1', 'Asta Cita 1'), ('2', 'Asta Cita 2'), ('3', 'Asta Cita 3'), ('4', 'Asta Cita 4'), ('5', 'Asta Cita 5'), ('6', 'Asta Cita 6'), ('7', 'Asta Cita 7'), ('8', 'Asta Cita 8')], max_length=2)),
                ('pkpn_klaster', models.CharField(blank=True, choices=[('pangan', 'Kedaulatan Pangan'), ('energi', 'Kemandirian Energi dan Air'), ('pendidikan', 'Pendidikan'), ('kesehatan', 'Kesehatan'), ('hilirisasi', 'Hilirisasi dan Industrialisasi'), ('infrastruktur', 'Infrastruktur Perumahan dan Ketahanan Bencana'), ('desa', 'Ekonomi Kerakyatan dan Desa'), ('kemiskinan', 'Penurunan Kemiskinan'), ('non_pkpn', 'Non PKPN')], max_length=20)),
                ('pkpn_program', models.CharField(blank=True, max_length=200)),
                ('mulai_uji_coba', models.DateField(blank=True, null=True)),
                ('mulai_penerapan', models.DateField(blank=True, null=True)),
                ('pengembangan_terbaru', models.DateField(blank=True, help_text='Wajib bila penerapan awal sebelum 2024 dan inovasi masih dikembangkan', null=True)),
                ('rancang_bangun', models.TextField(blank=True, help_text='Minimal 300 kata')),
                ('tujuan', models.TextField(blank=True)),
                ('manfaat', models.TextField(blank=True)),
                ('hasil', models.TextField(blank=True)),
                ('anggaran', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sumber_anggaran', models.CharField(blank=True, max_length=100)),
                ('pic_nama', models.CharField(blank=True, max_length=120)),
                ('pic_kontak', models.CharField(blank=True, max_length=60)),
                ('catatan_internal', models.TextField(blank=True, help_text='Tidak ikut diekspor ke IGA')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('diajukan', 'Menunggu verifikasi'), ('revisi', 'Perlu revisi'), ('terverifikasi', 'Terverifikasi')], default='draft', max_length=20)),
                ('catatan_verifikasi', models.TextField(blank=True)),
                ('diverifikasi_pada', models.DateTimeField(blank=True, null=True)),
                ('diajukan_pada', models.DateTimeField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inovasi_dibuat', to=settings.AUTH_USER_MODEL)),
                ('diverifikasi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifikasi', to=settings.AUTH_USER_MODEL)),
                ('opd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inovasi', to='inovasi.opd')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inovasi', to='inovasi.periode')),
            ],
            options={
                'verbose_name_plural': 'Inovasi',
                'ordering': ['-diperbarui_pada'],
            },
        ),
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(max_length=60)),
                ('objek', models.CharField(blank=True, max_length=120)),
                ('ringkasan', models.TextField(blank=True)),
                ('waktu', models.DateTimeField(default=django.utils.timezone.now)),
                ('pengguna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Log aktivitas',
                'ordering': ['-waktu'],
            },
        ),
        migrations.CreateModel(
            name='Indikator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspek', models.CharField(choices=[('spd', 'Satuan Pemerintah Daerah'), ('sid', 'Satuan Inovasi Daerah')], max_length=3)),
                ('nomor', models.PositiveSmallIntegerField(help_text='1-15 untuk SPD, 16-35 untuk SID')),
                ('sub', models.CharField(blank=True, help_text='a atau b bila indikator dipecah', max_length=2)),
                ('variabel', models.CharField(max_length=60)),
                ('nama', models.CharField(max_length=200)),
                ('bobot', models.DecimalField(decimal_places=2, max_digits=4)),
                ('wajib', models.BooleanField(default=False, help_text='Indikator mandatori')),
                ('parameter_1', models.CharField(max_length=250)),
                ('parameter_2', models.CharField(max_length=250)),
                ('parameter_3', models.CharField(max_length=250)),
                ('panduan', models.TextField(blank=True, help_text='Dokumen dukung yang diminta juknis')),
                ('aktif', models.BooleanField(default=True)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indikator', to='inovasi.periode')),
            ],
            options={
                'verbose_name_plural': 'Indikator',
                'ordering': ['nomor', 'sub'],
            },
        ),
        migrations.CreateModel(
            name='NilaiSID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilihan', models.PositiveSmallIntegerField(default=0, help_text='0 belum diisi, 1-3 parameter terpilih', validators=[django.core.validators.MaxValueValidator(3)])),
                ('basis_ukur', models.CharField(blank=True, help_text='Untuk indikator 33, basis a sampai f', max_length=2)),
                ('catatan', models.TextField(blank=True)),
                ('tautan', models.URLField(blank=True, max_length=500)),
                ('berkas', models.FileField(blank=True, upload_to=inovasi.models.path_bukti, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx', 'mp4'])])),
                ('verifikasi', models.CharField(choices=[('menunggu', 'Menunggu'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], default='menunggu', max_length=15)),
                ('catatan_verifikator', models.TextField(blank=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('diperbarui_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('diverifikasi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_sid', to='inovasi.indikator')),
                ('inovasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='inovasi.inovasi')),
            ],
            options={
                'verbose_name': 'Nilai SID',
                'verbose_name_plural': 'Nilai SID',
                'ordering': ['indikator__nomor'],
                'unique_together': {('inovasi', 'indikator')},
            },
        ),
        migrations.CreateModel(
            name='NilaiSPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilihan', models.PositiveSmallIntegerField(default=0, help_text='0 belum diisi, 1-3 parameter terpilih', validators=[django.core.validators.MaxValueValidator(3)])),
                ('keterangan', models.TextField(blank=True)),
                ('tautan', models.URLField(blank=True, max_length=500)),
                ('berkas', models.FileField(blank=True, upload_to='spd/%Y/')),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('diperbarui_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_spd', to='inovasi.indikator')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_spd', to='inovasi.periode')),
            ],
            options={
                'verbose_name': 'Nilai SPD',
                'verbose_name_plural': 'Nilai SPD',
                'ordering': ['indikator__nomor', 'indikator__sub'],
                'unique_together': {('periode', 'indikator')},
            },
        ),
        migrations.AddIndex(
            model_name='inovasi',
            index=models.Index(fields=['periode', 'opd', 'status'], name='inovasi_ino_periode_183bb8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='indikator',
            unique_together={('periode', 'nomor', 'sub')},
        ),
    ]
