# Generated by Django 5.2.17 on 2026-08-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inovasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periode',
            name='min_urusan_yandas',
            field=models.PositiveSmallIntegerField(default=6, help_text='Urusan wajib pelayanan dasar minimal. 6 (seluruhnya) mulai 2027.'),
        ),
        migrations.AlterField(
            model_name='periode',
            name='pembagi_minimal',
            field=models.PositiveSmallIntegerField(default=14, help_text='Jumlah inovasi pembagi rata-rata kematangan. 14 pada 2027, naik ke 16 (2028), 18 (2029).'),
        ),
    ]
